### ISSUE TITLE
Extracting session index from logout request

### ISSUE THREAD

**Issue by nickw444** [onelogin/python3-saml#32]
When handling a logout request, there doesn't seem to be a simple way to extract/obtain the session index from a logout request.

Is there such an API available to obtain this information?

Doing `auth.get_session_index()` returns `None`.

**Comment by pitbulk** [comment]
Yes, the LogoutRequest class has a [get_session_indexes](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/logout_request.py#L199) an this is an static method.

The auth.get_session_index() only works to retrieve the SessionIndex value from the SAMLResponse on the Assertion Consumer Service, and is set on the [process_response](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/auth.py#L114).

On the [process_slo](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/auth.py#L114) the logout request is processed, a logout response is generated and a redirection happens, so I'm not saving data on the $auth object since will be lost when executing the redirection.
Notice that the method has a delete_session_cb, so you will be able to pass a function that can take care of the SessionIndex and the session itself if you need it.

**Comment by nickw444** [comment]
Thanks. I ended up using get_session_indexes in my `delete_session_callback`:

```python
def delete_session_cb():
         sreq = req['get_data']['SAMLRequest']
         logout_request = OneLogin_Saml2_Utils.decode_base64_and_inflate(sreq, ignore_zip=True)
         indexes = OneLogin_Saml2_Logout_Request.get_session_indexes(logout_request)
         # ....do stuff with indexes...
```

Wouldn't a better API design be to pass the logout request to the session callback? (And possibly not use static methods, but rather directly retrieve the index from the request). 

The large use of static methods for things that are otherwise directly related to an instantiated logout request make this library really difficult to understand/use.

**Comment by pitbulk** [comment]
I think pass the logout request object makes totally sense.

**Comment by nickw444** [comment]
I'd love to contribute to the library, however currently not in a position to due to other commitments of my time. 

Closing this issue, since I did figure out how to achieve my goal in the end.
